### ISSUE TITLE
Linux: CMYK conversion is not yet supported on this platform

### ISSUE THREAD

**Issue by hheexx** [saucecontrol/PhotoSauce#103]
System.PlatformNotSupportedException
CMYK conversion is not yet supported on this platform.

We transcode a lot of differently sourced images. 
On some of them (<1%) we have this problem.

I just wanted to vote for supporting this, it's the only thing remaining that keep us on windows.

**Comment by saucecontrol** [comment]
Thanks for logging this.  Nice to see some feedback from Linux users already!

**Comment by hheexx** [comment]
Yea, we were ready to switch. 
Thanks for bringing Linux support faster then we expected :)

**Comment by saucecontrol** [comment]
This is handled in the latest [CI build](https://dev.azure.com/saucecontrol/PhotoSauce/_artifacts/feed/photosauce_ci).  You'll need to install `liblcms2` from your package manager to use it.

`liblcms2` will probably not be a long-term dependency.  It's quite slow, and I've already got a good deal of the needed functionality written in faster managed code.

**Comment by hheexx** [comment]
Thanks!
I will wait for release unless you want me to test before.....

**Comment by botinko** [comment]
Thank you very much for the Linux implementation. We have already started testing the library in our service. We have the same problem as in the topic.

**Comment by botinko** [comment]
Thank you very much for the Linux implementation. We have already started testing the library in our service. We have the same problem as in the topic.

**Comment by jasonliuplanetart** [comment]
thanks, this worked for me.

**Comment by hheexx** [comment]
@saucecontrol any plans for release soon?
If not it would be awesome if you could publish this to npm as beta.

**Comment by saucecontrol** [comment]
Depends on your definition of 'soon' 😄

I'm planning on putting out a new release once I complete xplat BMP and TIFF support to go with the color management that's already in.  Those are fairly close to done, but I've been buried in a client project since the start of the year and won't be able to dedicate significant time to completing them for at least a few more weeks.

The Azure CI NuGet feed is publicly accessible if you can't wait.

**Comment by hheexx** [comment]
We can wait few weeks no problem.
Just wanted to make sure it's not months.....

**Comment by hheexx** [comment]
@hheexx well.... it turned out to be months xD
any plan to release?

**Comment by saucecontrol** [comment]
Ha, yeah, I've been tied up rescuing a disaster of a project in my day job (my reward for rescuing a different project earlier in the year 😅).

It turns out implementing all the pixel format conversions that are required for TIFF support is messier than I anticipated and will require a bit of re-architecture.  I'll probably snap a release in the interim to get out the few improvements and fixes that I've done.

Won't be immediately, though, as I'd like to finish up some work I've been doing to set up PGO training sets for the native library builds before I release a new set of packages.

**Comment by jvillanueva-flipto** [comment]
was there any solution to this issue?

**Comment by saucecontrol** [comment]
> was there any solution to this issue?

Yep, the latest release will use `liblcms2` if present.  Should be available in your package manager.
