### ISSUE TITLE
ColorMatrixTransform does not unpremultiply/premultiply

### ISSUE THREAD

**Issue by rickbrew** [saucecontrol/PhotoSauce#131]
As per discussion on Discord. Color space conversions will not be correct for images that have alpha.

**Comment by saucecontrol** [comment]
I worked out the math on this again, and it doesn't make a difference whether you unpremultiply as long as you have enough precision (which we always do), because the proportions of the color values don't change with premultiplication, and that's all the color matrix does is blend the color channels based on their proportions.

I surely did this exercise when I first implemented it and came to the same conclusion, but at least now it's documented here, I won't forget again 😄
