### ISSUE TITLE
IMultiFrameDecoderOptions support missing for JPEG XL

### ISSUE THREAD

**Issue by MaceWindu** [saucecontrol/PhotoSauce#150]
Looks like JPEG XL supports animated images as https://jpegxl.info/test-page/ provides sampe animated jxl file.

**Comment by saucecontrol** [comment]
I have re-written the decoder plugin in https://github.com/saucecontrol/PhotoSauce/commit/c784500526d66ffe6ae14542ec76c98bacf0d9f7, and it now supports animation.

Skipping frames won't work for all images because of the way libjxl coalesces animation frames.  The sample on their test page does work, but any image containing frames that require a content from a previous frame may not have that content available if the frame was skipped.  Decoding a limited number of frames from the start of the image should always be fine.
