### ISSUE TITLE
BitsPerPixel

### ISSUE THREAD

**Issue by wahmedswl** [saucecontrol/PhotoSauce#20]
Hi,
   Is there anyway i can get BitsPerPixel of the Image loaded and also applied on the output Image? Any help would be appreciated.

Thanks

**Comment by saucecontrol** [comment]
Howdy!

I've got that information available within the pipeline, but it's not presently exposed in the API because it's mostly an implementation detail and may change during processing.  Can you elaborate a bit on what you might use it for?

In practice, the input bpp won't necessarily have any relation to the output bpp, and if your output is a compressed format, bpp may not have any real meaning at all.  If, for example, you start with an 80bpp CMYK image, that will be converted within the pipeline to a 24bpp BGR format, and if your output is JPEG, that will involve another conversion to Y'CbCr within the encoder.  And Y'CbCr JPEGs can be chroma-subsampled, so the true uncompressed bpp might be 12, 16, or 24 depending on subsampling.

Things are different if you're consuming the `IPixelSource` created by `MagicImageProcessor.BuildPipeline` since you need to know the exact data layout of that pixel data in order to use it.  For that case, the `IPixelSource` does expose its pixel format, which is always one of: 8bpp greyscale, 24bpp BGR, or 32bpp BGRA.  I'm working now on adding some explicit conversion transforms so that you can switch between those formats, but it will still be limited to those 3.

**Comment by wahmedswl** [comment]
Thanks for your quick response. We are migrating from Leadtools, so during save we can configure BPP, so is there anyway BPP can be set.

We are migrating due to speed, and we use 244 BPP and if its default then simple

```MagicImageProcessor.ProcessImage``` is sufficient.

Thanks

**Comment by saucecontrol** [comment]
Ah, I think I understand.  Right now, the input format does partially drive the output format.  If your input has transparency (you can check this with the `ImageFileInfo` `HasAlpha` property), your output will also have an alpha channel if the save format supports it.  It should be that setting an opaque `MatteColor` will change the output to RGB/BGR (dropping the alpha channel), but that is not currently the case.  I plan to have that fixed for the next version.

If you need control to explcitly set the output to one of the 3 formats I listed above, that will be possible in the next version as well.  I'm getting close to having that release ready.  Probably just another week or two.

**Comment by saucecontrol** [comment]
I've added a couple of things in v0.9.0:

1) If you use a `MatteColor` that is opaque, the output will be 24bpp BGR even if the input was RGBA/BGRA.
2) If you need to ensure a specific format regardless of input, you can use a custom pipeline and the `FormatConversionTransform` filter.  It would go something like this:

```C#
var settings = new ProcessImageSettings { Width = 400, SaveFormat = FileFormat.Png };
string inimg = @"c:\img\greyscale.jpg";
string outimg = @"c:\img\rgb.png";
using (var pipeline = MagicImageProcessor.BuildPipeline(inimg, settings))
{
    pipeline.AddTransform(new FormatConversionTransform(PixelFormats.Bgr24bpp));

    using (var fs = new FileStream(outimg, FileMode.Create))
        pipeline.ExecutePipeline(fs);
}
```
