### ISSUE TITLE
Preserve color space and color profiles

### ISSUE THREAD

**Issue by dungvt** [saucecontrol/PhotoSauce#23]
Hello everyone,
I have an image in CMYK space. When I resize this image to a smaller size, it will be forced to RGB space and wrong color profiles.
I have already read this issue: https://github.com/saucecontrol/PhotoSauce/issues/13, and my settings are:
```
MagicImageProcessor.ProcessImage(inputStream, output, new ProcessImageSettings
{
	Width = maxSize,
	Height = maxSize,
	ColorProfileMode = ColorProfileMode.Preserve,
	HybridMode = HybridScaleMode.FavorSpeed,
	ResizeMode = CropScaleMode.Max,
	SaveFormat = FileFormat.Jpeg,
	JpegQuality = quality
});
```
Color profile of my source image is "U.S. Web Coated (SWOP) v2" (CMYK). And although I have already installed it on my machine (https://i.imgur.com/ICpf01d.png), but my result image alway in uRGB.

My images:
Source: https://drive.google.com/open?id=1ciGXciq3GWzB8XAPriFcKwP3fuAgIuJF
Result: https://drive.google.com/open?id=1SuJQV53MNcHA3H86dgaq9-6dpBbQp8E_

Do you have any idea?

**Comment by saucecontrol** [comment]
Howdy, and thanks for the detailed report!

The behavior you describe is intentional.  MagicScaler was designed primarily around web imaging scenarios, so a forced conversion to a web-friendly format is expected by the majority of users.  It's fairly common for applications (mobile browsers and anything using System.Drawing/GDI+, for example) to do CMYK->RGB conversion incorrectly, so in most cases it makes sense to do that conversion inside the MagicScaler pipeline where we can assure it's done correctly.

Additionally, most image processing algorithms and file formats are defined only for RGB.  I recently updated the scaling algorithms in MagicScaler to support CMYK natively, but its other filters (including sharpening) assume RGB pixels, so preserving CMYK through the entire pipeline might require some sacrifices.

I'm curious about the requirement you have for resizing and preserving CMYK images, as it's not something I've seen any interest in.  Can you tell me more about your workflow?

**Comment by saucecontrol** [comment]
I changed the color profile handling in v0.11 https://github.com/saucecontrol/PhotoSauce/issues/51 and have updated the XML comments (and docs) to make it clear CMYK images are converted to Adobe RGB
