### ISSUE TITLE
[Question] Is there a way to copy the Exif data from 1 image to the output of a transform?

### ISSUE THREAD

**Issue by wahyuen** [saucecontrol/PhotoSauce#25]
Currently have a use case where I want to resize some images if they exceed a certain size, however, we would also like to preserve the exif metadata of the original image into the output of the new image.

I noticed in the documentation there was a `MetadataNames` property, however I'm struggling to find any examples of how to get this property to work. Is this type of functionality meant to be resolved using the above mentioned property? is there another way perhaps of achieving this?

**Comment by saucecontrol** [comment]
It will depend how much of the metadata you want to preserve.  The `MetadataNames` property allows you to explicitly select items to be copied to the output by using the [Windows Metadata Policy](https://docs.microsoft.com/en-us/windows/desktop/wic/photo-metadata-policies) names.  A common use case for that would be to ensure that copyright (the `System.Copyright` policy) is maintained.  The Windows Metadata Policies are good for explicit copying because they take care of differences in metadata location between different cotainer formats.

There is currently no provision for blindly copying all metadata from the source to destination.  Part of that is due to the fact the source file might have hundreds of KBs of garbage in it (Photoshop edit history for example), but there is also the issue of metadata that may become invalid when an image is resized, such as focal point, subject, or faces tags.

I'd be interested in gathering more requirements for metadata handling if you have some specific scenarios in mind.  The current handling is minimal, and the way writes are done using the Windows policies is not ideal.  I'd like to improve that going forward, but it currently meets my own needs, and I'm not sure what else people would be looking for.

**Comment by wahyuen** [comment]
Thanks for the prompt reply!

For our use case, we are currently looking to process mass amounts of imagery, and hoping to run this in parallel using serverless functions. As part of our image processing, we have found that call outs to numerous number of 3rd party services often have size (both file size and image dimension) limits. As such, we were looking into libraries that allowed us to scale down (resize) images to the appropriate dimensions, so that we could achieve a greater success rate of processing. 

Having looked at some other libraries, we would yours one of the best in terms of speed and memory (we quite often ran into OutOfMemoryExceptions using different libraries at our scale), but noticed that once the images were resized, we lost the associated EXIF data which we were using for other processing.

Perhaps it was my own naivety in this space thinking that I could blindly copy EXIF data across, you make a very valid point that some of it wouldn't actually make sense on the resized image! Again, many thanks for your response and your efforts into this library 👍
