### ISSUE TITLE
Please remove limitation on output stream

### ISSUE THREAD

**Issue by DarinMacRae** [saucecontrol/PhotoSauce#29]
I am trying to write directly to Azure Blob storage write stream and am getting an error that:

_Output_ Stream must allow Seek and Write_

There's no reason that you need to Seek when writing. Please remove this limitation to avoid having to buffer the write.

**Comment by saucecontrol** [comment]
That requirement comes from the WIC codecs.  I've just run a quick test, and the JPEG, BMP, GIF, and TIFF codecs all call `Seek` while encoding.  PNG didn't in my test, but I'm fairly certain I've seen it call `Seek` before as well.  I don't know why they do, but they do.

In any case, I wouldn't recommend writing directly to a network stream because the operation would be alternately CPU-bound (for the image processing) and IO-bound (for the blob storage) because of the way MagicScaler operates on slices of the output.  You're better off buffering the write and then copying to blob storage asynchronously to avoid tying up your thread for any longer than is already necessary.

**Comment by DarinMacRae** [comment]
Thank you. I appreciate the quick response and useful guidance. What you say makes good sense. I will use a MemoryStream as a buffer.
