### ISSUE TITLE
[Feature Request] Orientation

### ISSUE THREAD

**Issue by iamcarbon** [saucecontrol/PhotoSauce#3]
We've run into a few cases where we need to explicitly specify the orientation.

PROPOSAL:

```
ProcessorImageSettings {
   + Orientation Orientation { get; set; } 
}

// based on EXIF options
enum Orientation {
     Automatic, // default
     Horizontal,
     MirrorHorizontal,
     Rotate180 ,
     MirrorVertical,
     MirrorHorizontalAndRotate270,
     Rotate90 ,
     MirrorHorizontalAndRotate90,
     Rotate270
}
```

**Comment by saucecontrol** [comment]
I had been debating whether to allow overriding the auto-orientation behavior, and this is pretty much exactly what I came up with.  However, I had since talked myself out of it.

I had two main reasons for designing the auto-rotate behavior as it is now

1) Almost all modern software does orientation correction automatically, so it's increasingly common that people viewing an image don't know that it's stored in a different orientation.  I think applying that correction before any other processing is the most intuitive behavior and is the most consistent with other software.
2) Almost all orientation-tagged images are JPEG, and when accessing the WIC decoder directly, I can request that rotation in the frequency domain at very low cost.

So basically, it seemed like the right thing to do, and doing the right thing wasn't terrible for performance.

On the other hand, I had two scenarios where I could see overriding the default behavior being useful.

1) The orientation tag is present but incorrect.  I think in these cases, it's probably better to correct the tag than it is to try and find a way to override it, especially for consistency with other software.
2) The orientation tag isn't available because the metadata can't be accessed.  This was actually the case in the .NET Core version of MagicScaler up until a couple of weeks ago, but that's fixed now.

It sounds like your scenario matches the second, because you're feeding the image through the IPixelSource interface?  But of course this breaks the performance mitigation available in the WIC JPEG decoder.  In that case, it would be advantageous to do the flip/rotate post-resize, but then that changes the semantics of the crop/resize settings.

So my question to you is, would a post-resize flip/rotate filter be acceptable?  Or would you rather have the same behavior as the Exif-based orientation, even with its higher cost?

**Comment by iamcarbon** [comment]
Agreed -- users should never be concerned about orientation and it's best left to the decoder for performance. This use case can be easily handled upstream (orienting before we hit the pipeline) or downstream (orienting AFTER the scale & crop operations). 

In the later case, a flip and rotate filter (applied after the scaling & cropping) would be very handy.

**Comment by saucecontrol** [comment]
Cool.  I think a flip/rotate filter will make a nice use case for the filter API I'm working on.  I'll leave this issue open for that... Or in case anyone else has any input or a compelling case for the Exif override.

**Comment by saucecontrol** [comment]
I've just uploaded a new beta build to nuget with a basic filter plugin API and a couple of sample filters including a fliprotator.  Usage looks something like this:
```C#
using (var pl = MagicImageProcessor.BuildPipeline(@"c:\img\original.jpg", new ProcessImageSettings { Width = 400 }))
using (var fs = new FileStream(@"c:\img\output.jpg", FileMode.Create))
{
    pl.AddTransform(new OrientationTransform(Orientation.FlipVertical));
    pl.AddTransform(new ColorMatrixTransform(ColorMatrix.Negative));
    MagicImageProcessor.ExecutePipeline(pl, fs);
}
```
Let me know how that works for you...
