### ISSUE TITLE
SoA for convolution?

### ISSUE THREAD

**Issue by Ziriax** [saucecontrol/PhotoSauce#42]
First of all thanks for this amazing library! You really are an expert in this underestimated field, and sharing your knowledge in the form of code is invaluable.

I am contributing to SkiaSharp, and a high quality resampler is on my list. First I wanted to wrap the AVIR library, but your code seems very interesting too.

I was reading through your code, and was pleasantly surprised that you where already using the new SIMD intristics.

As far as I understand, you are using an AoS algorithm, working directly on the 4, 3 or 1 channel color structs, duplicating the kernel weights to that dimension

I was wandering, did you also try to implement an SoA version of this, as is done on the CoreCLR raytracer intrisric example?

Furthermore, I think bandwidth could be decreased by working on 16-bit floats as input, but at first sight .NET SIMD doesn't support that yet. Maybe 16-bit integers would also work...

Other thinks I would like to experiment with are streaming writes, more cache friendly image transposition, ...

I haven't worked with SIMD since SSE2, so my low level knowledge is very outdated, so sorry if none of this makes sense on modern CPUs ;-)

**Comment by saucecontrol** [comment]
Howdy!  Thanks for the kind words!

It's always nice to encounter someone with an interest in imaging algorithms and performance.  I've set up a [gitter channel](https://gitter.im/photosauce/Lobby) and just haven't added it to the readme yet.  Feel free to hop on there if you want to discuss possible work in that area.

> As far as I understand, you are using an AoS algorithm, working directly on the 4, 3 or 1 channel color structs, duplicating the kernel weights to that dimension

That's correct, mostly.  The majority use case for resizing in MagicScaler is JPEG in planar Y'CbCr format, so most of the work it does (in pure numbers of pixels processed) is SoA layout.  It may be possible to get some further gains by using SoA on BGR and BGRA data, however I have attempted to keep the algorithms working mostly the same between .NET Core and .NET Framework targets, and since there are no shuffle operations available on Framework, it's not practical to implement SoA.  And I'm actually quite pleased with the performance I've achieved using AoS with duplicated kernel weights.  The kernel weights are re-used, keeping them in CPU cache, so there probably isn't much to be gained once you factor in the cost of reorganizing the data before and after convolution.

> Furthermore, I think bandwidth could be decreased by working on 16-bit floats as input, but at first sight .NET SIMD doesn't support that yet. Maybe 16-bit integers would also work...

16-bit floats are a no-go for now, but you'll see I've implemented the pure scalar convolution in 16-bit integer for .NET Framework 32-bit targets, where legacy JIT doesn't support SIMD in any fashion and where floating-point math uses slow x87 instructions.  The same algorithms could be expanded to true SIMD, but again this would lead to less sharing between .NET Core and .NET Framework targets where SIMD is supported.  It's on my list for future exploration.

> Other thinks I would like to experiment with are streaming writes, more cache friendly image transposition, …

Again, please stop by the [gitter channel](https://gitter.im/photosauce/Lobby) if you'd like to chat about any possible improvements or are interested in contributing.  I'm always on the lookout for ideas :)
