### ISSUE TITLE
Fractional scaling impossible?

### ISSUE THREAD

**Issue by Ziriax** [saucecontrol/PhotoSauce#44]
As a follow up to #42, I started yesterday cooking my own AVX2 image downsampler that uses SoA. 

I still have a long way to go learning all the SIMD optimizations, but being a former Commodore Amiga assembly hacker, this is a lot of fun, and all in C#, amazing. I learned so much from your code!

Now when comparing my results with MagicScaler's, I noticed that I could only set the output image size in **integer pixels.**

So very smooth downscaling, in fractional pixel steps, doesn't seem possible?

Fractional scaling allows creating small thumbnails that retain the exact aspect ratio of the original, or to create a movie with very slowly scaling images with "pixel jumping".

This requires just a tiny change to the algoritm. But of course, this is not a feature people would need a lot ;-)

PS: I'm using the following MagicScaler settings for comparing:

```cs
new ProcessImageSettings
				{
					Width = dstWidth,
					Height = dstHeight,
					Sharpen = false,
					Interpolation = InterpolationSettings.Lanczos,
					HybridMode = HybridScaleMode.Off
				}
```

Using these settings, my current SoA SIMD implementation is a bit faster on my machine, but I guess magic scaler does a lot more internally. I also guess MagicScaler converts back to sRGB when outputting, something I don't do, since we need the images in a linear space. I also drop the alpha channel when processing an opaque image like JPEG.

Obviously when enabling hybrid scaling, and using the default interpolation setting, MagicScaler is 4 times faster, and because of  the sharpen, actually looks better ;-) I'm using images like [this one](https://c1.staticflickr.com/5/4202/34144634313_dde6fc1676_o.jpg) for testing

**Comment by saucecontrol** [comment]
> So very smooth downscaling, in fractional pixel steps, doesn't seem possible?

Yeah, this is something I considered originally, but since the pipeline was initially closed and always started with and ended with whole encoded pixels, it made sense to keep it simple.  I reckon most users are also confused by the concept of fractional pixels, which leaves the question of what happens to the part of the pixel that's undefined.  It makes more sense in a DrawImage implementation, where the area undefined by the operation can be understood to be the background.

As I've opened up the pipeline and exposed more of its innards directly, some of those initial design decisions make less sense, so I'm starting to consider what the API shape will look like going forward.  That will likely be my next are of focus after I tackle x-plat native codec integration and my final WIC dependencies.

I think at that point the extensible pipeline and the filters will end up separate from the one-shot ProcessImage that was the original API.  And a new name would be in order.

> Using these settings, my current SoA SIMD implementation is a bit faster on my machine, but I guess magic scaler does a lot more internally. I also guess MagicScaler converts back to sRGB when outputting

That sounds about right.  There's a certain breakover point where the kernel size and downscale ratio are high enough to justify the cost of reorganizing the data.  You may never hit that point using MagicScaler's default settings, which try to get the nicest looking image by doing the least amount of work.

> MagicScaler is 4 times faster, and because of the sharpen, actually looks better ;-)

That's the magic part :)
