### ISSUE TITLE
MagicScaler converts TIF to JPG when using FileFormat.Auto

### ISSUE THREAD

**Issue by zentaz** [saucecontrol/PhotoSauce#50]
Like the title says, when I'm resizing some TIF files I have they are converted to JPG in FileFormat.Auto mode.  PNGs are not converted, they remain as PNG, so I assume my code/settings are OK.

Just tested Image.RawFormat output for the files before resizing:

[ImageFormat: b96b3cb1-0728-11d3-9d7b-0000f81ef32e] tif
[ImageFormat: b96b3caf-0728-11d3-9d7b-0000f81ef32e] png
[ImageFormat: b96b3cae-0728-11d3-9d7b-0000f81ef32e] jpg

File headers are also OK before resizing, but after resize the TIF headers have changed to JPG format, and the new file size of the TIFs also match what you would expect after a JPG conversion.

There were some updates of some associated MS system files on NuGet after I installed MagicScaler, I wonder if they can be the cause?

**Comment by zentaz** [comment]
`  foreach (var imageFile in files)
           {
               string outputPath = @"H:\!test out";
               string outputFile = "";

               string fileName = Path.GetFileName(imageFile);
               string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(imageFile);

               string fileFormat = "";

               if (radioButtonFileFormatAuto.Checked)
               {
                   fileFormat = "auto";

                   outputFile = outputPath + "\\" + fileName;
               }
               else if (radioButtonFileFormatJpeg.Checked)
               {
                   fileFormat = "jpeg";

                   outputFile = outputPath + "\\" + fileNameWithoutExtension + ".jpg";
               }

               int jpegQuality = Convert.ToInt32(numericUpDownJpegQuality.Value);

               using (MemoryStream ms = new MemoryStream())
               {
                   var img = Image.FromFile(imageFile);
                   img.Save(ms, img.RawFormat);

                   int width = Convert.ToInt32(Convert.ToDecimal(img.Width) / 100 * Convert.ToInt32(numericUpDownResizeWidthPercentage.Value));

                   ResizeImage.Resize(ms, outputFile, width, fileFormat, jpegQuality);

                   img.Dispose();
                   ms.Dispose();
               }
           }
 public static void Resize(Stream image, string outPath, int width, string fileFormat, int jpegQuality)
        {
            ProcessImageSettings settings = null;

            if (fileFormat == "auto")
            {
                settings = new ProcessImageSettings { Width = width, SaveFormat = FileFormat.Auto, JpegQuality = jpegQuality };
            }

            if (fileFormat == "jpeg")
            {
                MessageBox.Show("jpg");

                settings = new ProcessImageSettings { Width = width, SaveFormat = FileFormat.Jpeg, JpegQuality = jpegQuality };
            }

            using (var outStream = new FileStream(outPath, FileMode.Create))
            {
                MagicImageProcessor.ProcessImage(image, outStream, settings);
            }
        }`

**Comment by saucecontrol** [comment]
That behavior is by design:

https://github.com/saucecontrol/PhotoSauce/blob/1f4af1e6f05edb9fb5feb89c1617d8d2bb9621a4/src/MagicScaler/Core/ProcessImageSettings.cs#L533-L541

The primary use case for MagicScaler is web output, so `FileFormat.Auto` will always result in a web-friendly output format.  TIFF and BMP output are supported primarily to allow uncompressed MagicScaler output to be fed into an external compressor, such as `cwebp` or `cjpeg`, which is why controls for TIFF compression are not available in `ProcessImageSettings`.

I'm in the process of re-designing codec support to allow for external codecs to be plugged in and for more granular control of those codec settings to be exposed.  I would be interested in knowing your use case for TIFF output if there's anything you can share.

In the meantime, if it's very important to you to maintain TIFF format (keeping in mind only uncompressed single frame output is supported), you can check the input format yourself with `ImageFileInfo.Load()` and use that to set `ProcessImageSettings.SaveFormat` to your desired type explicitly.

**Comment by zentaz** [comment]
Ah, OK, didn't know that, will try your suggestion then.   I'm currently writing some code for reducing the resolution of material files for 3D objects so they don't  use as many resources when rendering 3D scenes, it's important with a high quality resampling here.  In the context I'm working in only JPG, PNG and occasionally TIFF (single frame) are used.   I've also used MagicScaler in a catalog for 3D objects, to create high quality thumbnails.   It's a very useful tool in general so thanks for making it!

**Comment by saucecontrol** [comment]
Thanks for the update!

I think a manual settting of the output format should work for your case.  I'll update the docs to make it more clear what the `FileFormat.Auto` setting does.

**Comment by zentaz** [comment]
I've already got it implemented, it's working fine.  Currently I'm just using Image.RawFormat to get the file type as I'm using Image.FromFile anyway, but will take a look at ImageFileInfo.Load() to see if it may be faster.  Thanks again!

**Comment by saucecontrol** [comment]
Updated the XML comments to hopefully save anyone else this same trouble
