### ISSUE TITLE
CropScaleMode.Max gives unexpected results (upscaling)

### ISSUE THREAD

**Issue by mbengtson** [saucecontrol/PhotoSauce#52]
CropScaleMode.Max gives unexpected results (upscaling) when processing small images and only width or height is specified.

CropScaleMode.Max description: 
"Preserve the aspect ratio of the input image. Reduce one or both of the output dimensions if necessary to preserve the ratio but **never enlarge**."

The following has been tested on version 0.10.3 and a small 100x66 jpeg image as source.

**Example 1 - Both width and height is specified (OK)**

`MagicImageProcessor.ProcessImage(inputStream, outputStream, new ProcessImageSettings
{
	Width = 200,
	Height = 200,
	ResizeMode = CropScaleMode.Max
});`

Expected: 100x66 (not enlarged)
Actual: 100x66 (not enlarged)

**Example 2 - Only width is specified**

`MagicImageProcessor.ProcessImage(inputStream, outputStream, new ProcessImageSettings
{
	Width = 200,
	ResizeMode = CropScaleMode.Max
});`

Expected: 100x66 (not enlarged)
Actual: 200x132 (enlarged)

**Example 3 - Only height is specified**

`MagicImageProcessor.ProcessImage(inputStream, outputStream, new ProcessImageSettings
{
	Height = 200,
	ResizeMode = CropScaleMode.Max
});`

Expected: 100x66 (not enlarged)
Actual: 303x200 (enlarged)

Have I misunderstood what CropScaleMode.Max is supposed to do?
Is there any alternative solution that prevents upscaling?

Also, it would be great if there was an alternative to CropScaleMode.Pad which doesn't upscale the image but only pads/fills the canvas. Is there any way that this can be achieved already?

**Comment by saucecontrol** [comment]
Thanks for the detailed report.  This question was also asked in https://github.com/saucecontrol/PhotoSauce/issues/43, and I am currently considering whether to change the requirement that both Width and Height must be given for `CropScaleMode.Max` in the next release.

Currently, in `Max`, `Contain`, or `Pad` modes, the dimensions are taken as literal.  Since a width or height of `0` is nonsensical, the mode is switched to `Crop` during settings normalization.  `Crop` mode -- being the default -- has relaxed requirements for the size values, and it will attempt to correct/normalize your input so you get some meaningful result instead of an error.

Under the current definition of those settings, your intent is not `Width = 100, Height = 0`, but rather `Width = 100, Height = int.MaxValue`. In other words, you want the height to be practically unlimited.  This would be the workaround to get your desired behavior in the current version.

I think it's worth considering whether you really mean that, by making the setting explicit.  Take [this really long XKCD](https://imgs.xkcd.com/comics/earth_temperature_timeline.png) as an example.  Would you really want output of 100x2021 if you give `Width = 100, ResizeMode = CropScaleMode.Max`, or is there actually a height limit you would want?  And if you've decided there really isn't a limit, why not make that explicit by using `Height = int.MaxValue`?

> Also, it would be great if there was an alternative to CropScaleMode.Pad which doesn't upscale the image but only pads/fills the canvas. Is there any way that this can be achieved already?

Are you suggesting the output would be padded on all sides with an image of the original size in the middle? e.g. x 32x32 input with `Width = 100, Height = 100` would generate a 100x100 image that consists of the 32x32 original with 34px padding on each side?

**Comment by saucecontrol** [comment]
I went ahead and changed the settings normalization so that only `Pad` and `Stretch` modes require both width and height.  v0.11 is on NuGet now with the updated behavior.

**Comment by mbengtson** [comment]
Hi. Sorry about the late response.

**CropScaleMode.Max**
This now works as expected in v0.11 where width or height of 0 is treated as "no limit".
I could also have used the int.MaxValue which would have been fine too.

**CropScaleMode.Contain**
The behavior of this mode seems to have changed from v0.10 to v0.11.
It no longer maintains the aspect ratio when only width or height is specified (depending on original width/height ratio). Was that change intentional?

Example - Using CropScaleMode.Contain and Width only
Settings: Width = 250, Height = 0, ResizeMode = CropScaleMode.Contain
If the original image is 500x800 (portrait) then this will produce an image of 250x250 (wrong aspect ratio).
If the original image is 800x500 (landscape) then this will produce an image of 250x400 (ok).

A similar problem occurs with landscape images when only setting Height.

**CropScaleMode.Pad**
Yes, my suggestion was to have an alternative (CropScaleMode.PadMax?) which adds padding on all sides (depending on anchor) when the original image is smaller than specified width and height.
However, this is an edge case which probably doesn't make sense for everyone, so I completely understand if you don't want to add this.

**Comment by mbengtson** [comment]
I have reverted to using v0.10.3 and the different resize modes seems to work as expected. The only thing I had to change was to set int.MaxValue instead of 0 in Width or Height when using CropScaleMode.Max.
Now the only thing missing is a pad mode wit no upscaling, but I can live without it :)

**Comment by saucecontrol** [comment]
> There now seems to be an issue with aspect ratio though which also occurs with CropScaleMode.Contain

Yeah, thanks for pointing that out.  I think I confused myself when I put together the test cases.  The fix was still to set the missing value to `int.MaxValue` after removing the restriction that both values be present to start with.  I've pushed a new commit that does that.  You can try it out from the [CI build](https://dev.azure.com/saucecontrol/PhotoSauce/_packaging?_a=feed&feed=photosauce_ci) (I'll probably do a patch release to NuGet next week), or you can insert the `int.MaxValue` in your settings.

> Yes, my suggestion was to be able to pad with no upscaling (CropScaleMode.PadMax?) which adds padding on all sides (depending on anchor) when the original image is smaller than specified width and height.
However, this is an edge case which probably doesn't make sense for everyone, so I completely understand if you don't want to add this.

Cool, I think this gets a little too far into the drawing realm for my taste, at least for now.  I have plans to add some in-pipeline compositing for the purpose of adding watermarks and such, and this idea might fit in better at that point.  It's actually possible to piece this together with the API as is, but it would be so clumsy I wouldn't recommend it over just using SkiaSharp or ImageSharp for those edge cases.

**Comment by mbengtson** [comment]
Thanks for the quick response.
I'm actually doing a comparison of MagicScaler and SkiaSharp in order to decide which one to use for the project I'm working on. I like the simplicity and ease of use of MagicScaler and will probably go with that and accept the limitations. Right now the only thing that makes me lean towards SkiaSharp is the fact that it is cross-platform (not windows-only).
