### ISSUE TITLE
Is it possible to use ResizeMoode = CropScaleMode.Pad and MatteColor = Color.Transparent?

### ISSUE THREAD

**Issue by remmus** [saucecontrol/PhotoSauce#59]
I'm looking to make a number of PNGs the same size, padding the images either horizontally or vertically.

I thought this was working great with the following code

```
MagicImageProcessor.ProcessImage("C:\\input.png",
     new FileStream("C:\\output.png", FileMode.Create),
     new ProcessImageSettings()
     {
          Width = 3320,
          Height = 1500,
          ResizeMode = CropScaleMode.Pad,
          MatteColor = Color.Transparent,
          SaveFormat = FileFormat.Png
     }
);
```

The issue I am having is that where it has padded the height or width the background isn't transparent and is actually white. Am I doing something wrong, or does this not work how I expect?

Thanks for any support you can provide

**Comment by saucecontrol** [comment]
That should work.  It doesn't look like I have any test cases for Pad with transparent images, though, so I may have something broken.  I'll give it a look in a bit.

**Comment by saucecontrol** [comment]
On review, I do actually have test cases for this, and it does work as intended *if the source image has transparency*.  For non-transparent sources, the alpha channel in the `MatteColor` is ignored to avoid an unnecessary format conversion for the whole image.  And since `Color.Transparent` is actually defined as `0x00FFFFFF`, when the alpha channel is ignored, it yields solid white padding.

It seems reasonable to expect that a transparent or semi-transparent matte color should work when padding an image of any format, so I'm going to go ahead and change that behavior.

**Comment by remmus** [comment]
Thanks so much for your support on this @saucecontrol really appreciated you looking into this so quickly

**Comment by saucecontrol** [comment]
No problem!  Thanks for bringing that to my attention.  New release is up with the fix.

**Comment by remmus** [comment]
Tested and all works! Thanks again for your time on this. Hugely appreciated
