### ISSUE TITLE
IYccImageFrame Regression in 0.12.1

### ISSUE THREAD

**Issue by iamcarbon** [saucecontrol/PhotoSauce#78]
When upgrading from 0.12.0 -> 0.12.1, some Ycc data seems to be corrupted.

Sample output images attached. Test case coming soon.

**Comment by iamcarbon** [comment]
<img width="56" alt="12 0" src="https://user-images.githubusercontent.com/7537/133960867-44dff53d-0102-4e1a-b71e-690fc31a0d68.png">
<img width="59" alt="12 1" src="https://user-images.githubusercontent.com/7537/133960869-fa6f85da-8e92-4be5-be25-85e509def044.png">

**Comment by saucecontrol** [comment]
Just eyeballing it, I'd guess the chroma values are getting left with their offset values (encoded value - 128) instead of being corrected prior to encoding/conversion.  Nothing jumps out at me as a cause from the diff between releases, but 0.12.1 did fix some cases where chroma was left intact when it should have been processed.  Could be the offset is getting double applied here or isn't getting reversed after processing somehow.

If you don't have time to put together a full repro, some info about the workflow might be enough to help me track it down.

**Comment by iamcarbon** [comment]
Test case attached.

[R1.zip](https://github.com/saucecontrol/PhotoSauce/files/7232229/R1.zip)

**Comment by saucecontrol** [comment]
Oh wow, I was looking in the wrong place entirely.  The bug was in the refactoring of the outer planar pipeline.

When you have an `IYccImageFrame` source with 4:2:0 subsampling *and* have hybrid scaling enabled *and* the hybrid scale ratio works out to 2:1, only the luma plane needs to pass through the hybrid scale filter because the chroma planes are already at the target size.  In 0.12.1, it's passing all 3 planes through the filter, and since the filter has nothing to do for the chroma planes, they don't get written out at all.  The bug doesn't get hit with JPEG sources since the hybrid scale step is serviced by the decoder in that case.

Quick workaround is to set `HybridMode = HybridScaleMode.Off` for `IYccImageFrame` sources.  I'll put out a patch release this week.

**Comment by saucecontrol** [comment]
Fixed in v0.12.2.  Note that the attached test case will fail with the new release because of the aforementioned fix to chroma processing on sources specifying video (16-240) chroma levels.  The output from 0.12.2 is correct in this case.
