### ISSUE TITLE
Would it be possible to add a pure RGB mode to the JpegEncoderOptions?

### ISSUE THREAD

**Issue by omaximenco** [saucecontrol/PhotoSauce#86]
First of all I just wanted to say thanks @saucecontrol for this super awesome library and your efforts on building and maintaining it. I'm using it in my personal project after switching from the lackluster SkiaSharp.

Now, is there a way to use a pure RGB option to render jpegs?
ChromaSubsampleMode.Subsample444 is still using chroma subsampling (4:4:4) in spite of the enum comment mentioning "Do not use chroma subsampling".

**Comment by saucecontrol** [comment]
Howdy!  Thanks for the kind words.

Firstly, let me attempt to clear up a possible point of confusion.  Chroma *subsampling* refers to formats in which only a sampled *subset* of chroma values are encoded. Although 4:4:4 is usually included in discussions of subsampling, it does strictly mean no subsampling is performed -- the chroma values are encoded at full resolution.

Orthogonal to that would be the question of skipping the RGB to Y'CbCr (luma+chroma) transform entirely.  That's not currently possible because the Windows JPEG encoder doesn't support it, but I am working on supporting `libjpeg` as a plugin, which would enable it.

I am skeptical, however, about the usefulness of that option.  Although RGB->YCbCr->RGB is not an entirely lossless transform, JPEG itself is not a lossless format, and separation of luma and chroma data is a key part of the compressibility of JPEG.  More modern formats like lossless WebP (coming soon) or even PNG will generally give better results than any attempt at making a near-lossless JPEG.

Is there some specific use case I'm missing that would make that option worthwhile?

**Comment by omaximenco** [comment]
@saucecontrol You're absolutely right concerning the usefulness, but let me explain where I'm coming from. I spent the past weekend testing MagicScaler and ImageSharp in terms of processing speed and quality, and realized I'm getting some visible banding even at 100% JPEG quality in MagicScaler / 4:4:4 /  Lanczos / no sharpening. The pure RGB option I got from ImageSharp did not produce banding., which gave me an idea that 4:4:4 != RGB. If you click on the second photo https://photostream.us/ - you'll see what I mean. JPEG is delivered by MagicScaler, WebP by Skia. If you go to "Settings" and switch to PNG (MagicScaler) - most of the banding will be gone.

I ran a few more tests, and as you're saying I could get a 24-bit PNG file of the same size or even slightly smaller compared to an RGB JPEG q=100. So maybe it doesn't make much sense at all, and maybe it's not even worth an enhancement/feature request...

Concerning the lossless WebP - I think it has the same problem as lossless JPEG - the file size would be same or bigger compared to 24-bit PNG (tested via ImageSharp).
I could be wrong but I think WebP is focused around 4:2:0 sub sampling. I ran a few tests via both Skia and ImageSharp, and lossy results do not look good to me in general, even at q=100. Yes, the files are small, but... terrible :)

I'm looking forward to trying your WebP implementation when it's ready. Right now I'm keeping Skia for WebP, but I think it doesn't handle color profiles correctly, even sRGB. ImageSharp is just too slow. MagicScaler is the future! 👍

**Comment by saucecontrol** [comment]
Very interesting.  I do see what you mean about the banding (nice site BTW!).  I'll have to see if there's anything we can do on the JPEG side to reduce that.  It could be a matter of chroma encoding using more aggressive quantization tables compared to luma, while encoding RGB forces the encoder to use the same tables for all 3 color planes.  The main motivation for integrating libjpeg is Linux compatability, but it will also allow a lot more control over encoding parameters than the Windows encoder does.

And you're right about WebP lossy; it only supports 4:2:0 subsampling regardless of quality setting.  They made some "interesting" design choices in the implementation as well.  I'm currently making some changes to my pipeline to accommodate WebP's planar format and its inconsistency with the way JPEG (or anything else) works.

I haven't played much with WebP lossless on high-res photos, so I'm not sure if it does better than PNG compression-wise for that type of content.  Will do some testing once I have that wired up in my pipeline.

**Comment by omaximenco** [comment]
Thank you and please don't waste your time on this. That particular image (along with other 5 from the same photo shoot) had a pretty busy background (the forest piece). I had to add some Gaussian blur (r=30) to the forest in Photoshop. Based on my experience that's a very good recipe for banding :)   I should have added some noise over that blur - that would help to avoid banding, but I didn't. So that's basically a worst case scenario. Those super smooth gradations/transitions in the source image will always produce visible banding with _any_ lossy compression method.
Also, if it helps to contribute to the project - I'll be more than happy to provide any kind of high res images, and my site code as well. Unfortunately it's not packageable at the moment (I never planned to do anything with it but to use as a personal web gallery), but it's pretty easy to deploy nevertheless (.Net6 + Angular 14 + PgSql).
Thanks!
