### ISSUE TITLE
[Feature Request] AVIF Decoder

### ISSUE THREAD

**Issue by iamcarbon** [saucecontrol/PhotoSauce#97]
AVIF images are becoming more common on the web, and would be useful to be able to decode in MagicScaler.

This is an issue to determine the feasibility of an adding a native AVIF decoder, using libheif's (+libaom), or the [libavif](https://github.com/AOMediaCodec/libavif) libraries.

**Comment by saucecontrol** [comment]
Adding aom to the libheif build is easy enough, so I'll go ahead and do that short-term.  My longer term plan was to ditch libheif in favor of handling the container managed-side and using libde265 directly for the frame decode.  I'll have to give libavif a look and see if it's any better.

**Comment by saucecontrol** [comment]
I went ahead and added [dav1d](https://code.videolan.org/videolan/dav1d) to the libheif build since it's reached stable now and is quite a bit faster than aom.  I've only done minimal testing so far, but it's loking good.

Package is up on the [CI feed](https://dev.azure.com/saucecontrol/PhotoSauce/_artifacts/feed/photosauce_ci) if anybody wants to check it out.

**Comment by iamcarbon** [comment]
Awesome!

One small issue trying out the CI feeds:

Nuget seems to consider prereleases (-ci...) to be < a full release, so these unreleased dependencies don't resolve when using package ranges (e.g. >= 0.13.2) [as there's no 0.13.2 release].

<img width="697" alt="Screen Shot 2022-10-15 at 1 31 00 PM" src="https://user-images.githubusercontent.com/7537/196006408-fc039eae-6d7d-4d44-b7b0-851730902d8a.png">

<img width="1049" alt="Screen Shot 2022-10-15 at 1 21 20 PM" src="https://user-images.githubusercontent.com/7537/196006395-4944b0ee-110a-45eb-a04d-13f9fae75273.png">

I'll give a local build a try later!

**Comment by saucecontrol** [comment]
Ah, thanks for the heads up on that. I'll see if I can work out a better way to set up the package dependencies so they update together. There was some internal refactoring that means the native codecs do actually require the 0.13.2 preview of the main lib, so you could reference the `0.13.2-ci*` version of the main lib explicitly, I believe.

**Comment by saucecontrol** [comment]
Oh! I remember why they're set up that way. The msbuild task that sets the dependency range was messing up release builds because I've pushed release versions of the main lib together with preview versions of the native codec packages. The fix for that is what's breaking the -ci dependency versions. I can fix that 😄

**Comment by iamcarbon** [comment]
@saucecontrol ^ that fix worked! Will keep you updated on how it works in production!

**Comment by saucecontrol** [comment]
Package is up on [nuget.org](https://www.nuget.org/packages/PhotoSauce.NativeCodecs.Libheif/1.13.0-preview1)
